import java.awt.FontFormatException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */


/**
 *
 * @author hezekiahmagalona
 */
public class editorder extends javax.swing.JPanel {
    
    private Connection conn;
    private java.awt.Font customFont;


    /**
     * Creates new form customer
     */

    public editorder() {
        initComponents();
        loadFonts();
        
         loadCustomerIDs(); 
         loadAffiliateIDs();
        
        ((javax.swing.JTextField) orderdate.getDateEditor().getUiComponent()).setEditable(false);
        ((javax.swing.JTextField) duedate.getDateEditor().getUiComponent()).setEditable(false);
        
        customerid.setUI(new javax.swing.plaf.basic.BasicComboBoxUI());
        customerid.setBackground(java.awt.Color.WHITE);
        customerid.setForeground(java.awt.Color.BLACK);
        
        affiliateid.setUI(new javax.swing.plaf.basic.BasicComboBoxUI());
        affiliateid.setBackground(java.awt.Color.WHITE);
        affiliateid.setForeground(java.awt.Color.BLACK);

        oID.setFont(customFont.deriveFont(java.awt.Font.BOLD, 28f));
        odate.setFont(customFont.deriveFont(java.awt.Font.BOLD, 28f));
        oduedate.setFont(customFont.deriveFont(java.awt.Font.BOLD, 28f));
        oprog.setFont(customFont.deriveFont(java.awt.Font.BOLD, 28f));
        ocID.setFont(customFont.deriveFont(java.awt.Font.BOLD, 28f));
        oaID.setFont(customFont.deriveFont(java.awt.Font.BOLD, 28f));
        
        generateNextOrderID();
    }
     private void loadCustomerIDs() {
        String sql = "SELECT customer_id FROM Customers ORDER BY customer_id";
    try (Connection conn = getConnection();
         PreparedStatement pst = conn.prepareStatement(sql);
         ResultSet rs = pst.executeQuery()) {

        customerid.removeAllItems();
        while (rs.next()) {
            customerid.addItem(String.valueOf(rs.getInt("customer_id")));
        }
                customerid.setSelectedIndex(-1);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Failed to load customers: " + e.getMessage());
    }
}
     
      private void loadAffiliateIDs() {
        String sql = "SELECT affiliate_id FROM Affiliates ORDER BY affiliate_id";
        try (Connection conn = getConnection();
             PreparedStatement pst = conn.prepareStatement(sql);
             ResultSet rs = pst.executeQuery()) {

            affiliateid.removeAllItems();
            affiliateid.addItem("");
            
            while (rs.next()) {
                affiliateid.addItem(rs.getString("affiliate_id"));
            }
            affiliateid.setSelectedIndex(0); 

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Failed to load affiliates: " + e.getMessage());
        }
    }
    
    
    private Connection getConnection() throws Exception {
    String url = "jdbc:sqlserver://localhost:1433;"
        + "databaseName=ifcdb;"
        + "encrypt=true;"
        + "trustServerCertificate=true";

    String user = "sa";
    String password = "Anolagam28";

    return DriverManager.getConnection(url, user, password);
    }


    private void generateNextOrderID() {
        try {
            java.sql.Connection conn = getConnection();

            String sql = "SELECT MAX(order_id) AS max_id FROM Orders";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery();

            int nextID = 3000;

            if (rs.next()) {
                int maxID = rs.getInt("max_id");

                if (!rs.wasNull()) {
                    nextID = maxID + 1;
                }
            }

            orderID.setText(String.valueOf(nextID));

            rs.close();
            pst.close();
            conn.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Failed to generate Order ID: " + e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progress = new javax.swing.ButtonGroup();
        affiliateid = new javax.swing.JComboBox<>();
        customerid = new javax.swing.JComboBox<>();
        duedate = new com.toedter.calendar.JDateChooser();
        orderdate = new com.toedter.calendar.JDateChooser();
        orderID = new javax.swing.JTextField();
        clear = new javax.swing.JButton();
        save = new javax.swing.JButton();
        backtotable = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        producttype = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        odate = new javax.swing.JLabel();
        oduedate = new javax.swing.JLabel();
        ocID = new javax.swing.JLabel();
        oID = new javax.swing.JLabel();
        oprog = new javax.swing.JLabel();
        oaID = new javax.swing.JLabel();
        producttype1 = new javax.swing.JLabel();
        done = new javax.swing.JRadioButton();
        notstarted = new javax.swing.JRadioButton();
        inprogress = new javax.swing.JRadioButton();
        mainbg = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        affiliateid.setBackground(new java.awt.Color(255, 255, 255));
        affiliateid.setFont(new java.awt.Font("Kokonor", 0, 24)); // NOI18N
        affiliateid.setForeground(new java.awt.Color(0, 0, 0));
        affiliateid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Inactive", "Expired" }));
        affiliateid.setSelectedIndex(-1);
        affiliateid.setPreferredSize(new java.awt.Dimension(133, 65));
        affiliateid.addActionListener(this::affiliateidActionPerformed);
        add(affiliateid, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 560, 380, 50));

        customerid.setBackground(new java.awt.Color(255, 255, 255));
        customerid.setFont(new java.awt.Font("Kokonor", 0, 24)); // NOI18N
        customerid.setForeground(new java.awt.Color(0, 0, 0));
        customerid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Inactive", "Expired" }));
        customerid.setSelectedIndex(-1);
        customerid.setPreferredSize(new java.awt.Dimension(133, 65));
        customerid.addActionListener(this::customeridActionPerformed);
        add(customerid, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 480, 380, 50));

        duedate.setBackground(new java.awt.Color(255, 255, 255));
        duedate.setForeground(new java.awt.Color(0, 0, 0));
        duedate.setFont(new java.awt.Font("Kokonor", 0, 24)); // NOI18N
        duedate.setOpaque(false);
        add(duedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, 370, 50));

        orderdate.setBackground(new java.awt.Color(255, 255, 255));
        orderdate.setForeground(new java.awt.Color(0, 0, 0));
        orderdate.setFont(new java.awt.Font("Kokonor", 0, 24)); // NOI18N
        orderdate.setOpaque(false);
        add(orderdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, 370, 50));

        orderID.setBackground(new java.awt.Color(255, 255, 255));
        orderID.setFont(new java.awt.Font("Baskerville", 0, 24)); // NOI18N
        orderID.setForeground(new java.awt.Color(0, 0, 0));
        orderID.setBorder(null);
        add(orderID, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 370, 50));

        clear.setBackground(new java.awt.Color(255, 255, 255));
        clear.setFont(new java.awt.Font("Kokonor", 0, 18)); // NOI18N
        clear.setForeground(new java.awt.Color(0, 0, 0));
        clear.setText("Clear");
        clear.addActionListener(this::clearActionPerformed);
        add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 660, 120, 40));

        save.setBackground(new java.awt.Color(255, 255, 255));
        save.setFont(new java.awt.Font("Kokonor", 0, 18)); // NOI18N
        save.setForeground(new java.awt.Color(0, 0, 0));
        save.setText("Save");
        save.addActionListener(this::saveActionPerformed);
        add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 660, 120, 40));

        backtotable.setBackground(new java.awt.Color(255, 255, 255));
        backtotable.setFont(new java.awt.Font("Kokonor", 0, 18)); // NOI18N
        backtotable.setForeground(new java.awt.Color(0, 0, 0));
        backtotable.setText("Back to Table");
        backtotable.setToolTipText("");
        backtotable.addActionListener(this::backtotableActionPerformed);
        add(backtotable, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 660, 150, 40));

        delete.setBackground(new java.awt.Color(255, 255, 255));
        delete.setFont(new java.awt.Font("Kokonor", 0, 18)); // NOI18N
        delete.setForeground(new java.awt.Color(0, 0, 0));
        delete.setText("Delete");
        delete.addActionListener(this::deleteActionPerformed);
        add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 660, 120, 40));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ifccrafts/assets/tfield.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, -1, 70));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ifccrafts/assets/tfield.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, -1, 70));

        producttype.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        producttype.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ifccrafts/assets/tfield.png"))); // NOI18N
        add(producttype, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 470, -1, 70));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ifccrafts/assets/tfield.png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, -1, 70));

        odate.setFont(new java.awt.Font("Big Caslon", 0, 24)); // NOI18N
        odate.setForeground(new java.awt.Color(255, 255, 255));
        odate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        odate.setText("Order Date:");
        add(odate, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 180, 50));

        oduedate.setFont(new java.awt.Font("Big Caslon", 0, 24)); // NOI18N
        oduedate.setForeground(new java.awt.Color(255, 255, 255));
        oduedate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        oduedate.setText("Due Date:");
        add(oduedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 180, 50));

        ocID.setFont(new java.awt.Font("Big Caslon", 0, 24)); // NOI18N
        ocID.setForeground(new java.awt.Color(255, 255, 255));
        ocID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ocID.setText("Customer ID:");
        add(ocID, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 480, 240, 50));

        oID.setFont(new java.awt.Font("Big Caslon", 0, 24)); // NOI18N
        oID.setForeground(new java.awt.Color(255, 255, 255));
        oID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        oID.setText("Order ID:");
        add(oID, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 170, 50));

        oprog.setFont(new java.awt.Font("Big Caslon", 0, 24)); // NOI18N
        oprog.setForeground(new java.awt.Color(255, 255, 255));
        oprog.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        oprog.setText("Progress:");
        add(oprog, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 240, 50));

        oaID.setFont(new java.awt.Font("Big Caslon", 0, 24)); // NOI18N
        oaID.setForeground(new java.awt.Color(255, 255, 255));
        oaID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        oaID.setText("Affiliate ID:");
        add(oaID, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 560, 240, 50));

        producttype1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        producttype1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ifccrafts/assets/tfield.png"))); // NOI18N
        add(producttype1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 550, -1, 70));

        progress.add(done);
        done.setFont(new java.awt.Font("Kokonor", 0, 24)); // NOI18N
        done.setForeground(new java.awt.Color(255, 255, 255));
        done.setText("Done");
        done.setToolTipText("");
        done.addActionListener(this::doneActionPerformed);
        add(done, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 396, -1, 60));

        progress.add(notstarted);
        notstarted.setFont(new java.awt.Font("Kokonor", 0, 24)); // NOI18N
        notstarted.setForeground(new java.awt.Color(255, 255, 255));
        notstarted.setText("Not Started");
        add(notstarted, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 396, -1, 60));

        progress.add(inprogress);
        inprogress.setFont(new java.awt.Font("Kokonor", 0, 24)); // NOI18N
        inprogress.setForeground(new java.awt.Color(255, 255, 255));
        inprogress.setText("In Progress");
        inprogress.addActionListener(this::inprogressActionPerformed);
        add(inprogress, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 396, -1, 60));

        mainbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ifccrafts/assets/mainbg.png"))); // NOI18N
        add(mainbg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        try {
        String orderIDText = orderID.getText().trim();

        // 1. Check if the Order ID itself is empty
        if (orderIDText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter an Order ID to delete.");
            return;
        }

        // 2. Safely grab text from the combo boxes and other inputs
        Object selectedCustomer = customerid.getSelectedItem();
        Object selectedAffiliate = affiliateid.getSelectedItem();
        
        String customerText = (selectedCustomer != null) ? selectedCustomer.toString().trim() : "";
        String affiliateText = (selectedAffiliate != null) ? selectedAffiliate.toString().trim() : "";
        
        java.util.Date orderDateValue = orderdate.getDate();
        java.util.Date dueDateValue = duedate.getDate();

        // 3. Check if ANY other field has actual data in it
        boolean hasOtherFields = !customerText.isEmpty() 
                || !affiliateText.isEmpty() 
                || orderDateValue != null 
                || dueDateValue != null 
                || notstarted.isSelected() 
                || inprogress.isSelected() 
                || done.isSelected();

        if (hasOtherFields) {
            JOptionPane.showMessageDialog(this, "Only Order ID should have a value when deleting.");
            return;
        }

        // 4. Proceed with confirmation and database deletion
        int confirm = JOptionPane.showConfirmDialog(
                this, 
                "Are you sure you want to permanently delete Order ID " + orderIDText + "?", 
                "Confirm Delete", 
                JOptionPane.YES_NO_OPTION, 
                JOptionPane.WARNING_MESSAGE
        );

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        // 5. Execute Delete Query
        try (java.sql.Connection conn = getConnection();
             java.sql.PreparedStatement pst = conn.prepareStatement("DELETE FROM Orders WHERE order_id = ?")) {
            
            pst.setInt(1, Integer.parseInt(orderIDText));
            int rowsDeleted = pst.executeUpdate();

            if (rowsDeleted > 0) {
                JOptionPane.showMessageDialog(this, "Order deleted successfully.");
                
                // Clear the form fields completely
                orderID.setText("");
                orderdate.setDate(null);
                duedate.setDate(null);
                progress.clearSelection();
                customerid.setSelectedIndex(-1);
                affiliateid.setSelectedIndex(-1);
            } else {
                JOptionPane.showMessageDialog(this, "Order ID not found in the database.");
            }
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Order ID must be a valid number.");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Delete failed: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_deleteActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
         int response = JOptionPane.showConfirmDialog(
            this,
            "This will clear all your inputs. Continue?",
            "Confirm Clear",
            JOptionPane.YES_NO_OPTION
    );

    if (response == JOptionPane.YES_OPTION) {
        orderID.setText("");
        orderdate.setDate(null);
        duedate.setDate(null);
        progress.clearSelection();
        
        // Force both dropdowns to reset to an empty selection (-1)
        customerid.setSelectedIndex(-1);
        affiliateid.setSelectedIndex(-1);

        JOptionPane.showMessageDialog(this, "Fields cleared successfully.");
    }
    }//GEN-LAST:event_clearActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        try {
        java.sql.Connection conn = getConnection();

        String orderIDText = orderID.getText().trim();
        
        // Safely extract the items from the combo boxes
        Object selectedCustomer = customerid.getSelectedItem();
        Object selectedAffiliate = affiliateid.getSelectedItem();
        
        String customerIDText = (selectedCustomer != null) ? selectedCustomer.toString().trim() : "";
        String affiliateIDText = (selectedAffiliate != null) ? selectedAffiliate.toString().trim() : "";
        
        java.util.Date orderDateValue = orderdate.getDate();
        java.util.Date dueDateValue = duedate.getDate();
        String progressStatus = "";

        if (notstarted.isSelected()) {
            progressStatus = "Not Started";
        } else if (inprogress.isSelected()) {
            progressStatus = "In Progress";
        } else if (done.isSelected()) {
            progressStatus = "Done";
        }

        // Validate required inputs
        if (orderDateValue == null
                || dueDateValue == null
                || customerIDText.isEmpty()
                || progressStatus.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all required fields.");
            conn.close();
            return;
        }

        java.sql.Date sqlOrderDate = new java.sql.Date(orderDateValue.getTime());
        java.sql.Date sqlDueDate = new java.sql.Date(dueDateValue.getTime());

        if (sqlDueDate.before(sqlOrderDate)) {
            JOptionPane.showMessageDialog(this, "Due date should be after the order date.");
            conn.close();
            return;
        }

        int customerIDValue;
        try {
            customerIDValue = Integer.parseInt(customerIDText);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Customer ID must be a number.");
            conn.close();
            return;
        }

        // Check if Customer ID exists
        java.sql.PreparedStatement checkCustomer = conn.prepareStatement("SELECT * FROM Customers WHERE customer_id = ?");
        checkCustomer.setInt(1, customerIDValue);
        java.sql.ResultSet customerRS = checkCustomer.executeQuery();
        if (!customerRS.next()) {
            JOptionPane.showMessageDialog(this, "Customer ID does not exist.");
            customerRS.close();
            checkCustomer.close();
            conn.close();
            return;
        }
        customerRS.close();
        checkCustomer.close();

        // Check if Affiliate ID exists (if provided)
        if (!affiliateIDText.isEmpty()) {
            java.sql.PreparedStatement checkAffiliate = conn.prepareStatement("SELECT * FROM Affiliates WHERE affiliate_id = ?");
            checkAffiliate.setString(1, affiliateIDText);
            java.sql.ResultSet affiliateRS = checkAffiliate.executeQuery();
            if (!affiliateRS.next()) {
                JOptionPane.showMessageDialog(this, "Affiliate ID does not exist.");
                affiliateRS.close();
                checkAffiliate.close();
                conn.close();
                return;
            }
            affiliateRS.close();
            checkAffiliate.close();
        }

        // Check if Order ID already exists
        Integer orderIDValue = null;
        if (!orderIDText.isEmpty()) {
            try {
                orderIDValue = Integer.parseInt(orderIDText);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Order ID must be a number.");
                conn.close();
                return;
            }

            java.sql.PreparedStatement checkOrder = conn.prepareStatement("SELECT * FROM Orders WHERE order_id = ?");
            checkOrder.setInt(1, orderIDValue);
            java.sql.ResultSet orderRS = checkOrder.executeQuery();

            if (orderRS.next()) {
                JOptionPane.showMessageDialog(this, "Order ID already exists.");
                orderRS.close();
                checkOrder.close();
                conn.close();
                return;
            }
            orderRS.close();
            checkOrder.close();
        }

        // Display summary confirmation dialog
        String summary = "Are you sure you want to save this?\n\n"
                + "Order ID: " + (orderIDValue != null ? orderIDValue : "(Auto-Generated)") + "\n"
                + "Order Date: " + sqlOrderDate + "\n"
                + "Due Date: " + sqlDueDate + "\n"
                + "Progress: " + progressStatus + "\n"
                + "Customer ID: " + customerIDText + "\n"
                + "Affiliate ID: " + (affiliateIDText.isEmpty() ? "None" : affiliateIDText);

        int confirm = JOptionPane.showConfirmDialog(this, summary, "Confirm Save", JOptionPane.YES_NO_OPTION);

        if (confirm != JOptionPane.YES_OPTION) {
            conn.close();
            return;
        }

        String sql;
        java.sql.PreparedStatement pst;

        // Identity override handling based on custom vs auto-generated IDs
        if (orderIDValue != null) {
            sql = """
                  SET IDENTITY_INSERT Orders ON;
                  INSERT INTO Orders
                  (order_id, order_date, due_date, order_status, customer_id, affiliate_id)
                  VALUES (?, ?, ?, ?, ?, ?);
                  SET IDENTITY_INSERT Orders OFF;
                  """;
            pst = conn.prepareStatement(sql);
            pst.setInt(1, orderIDValue);
            pst.setDate(2, sqlOrderDate);
            pst.setDate(3, sqlDueDate);
            pst.setString(4, progressStatus);
            pst.setInt(5, customerIDValue);

            if (affiliateIDText.isEmpty()) {
                pst.setNull(6, java.sql.Types.VARCHAR);
            } else {
                pst.setString(6, affiliateIDText);
            }
        } else {
            sql = """
                  INSERT INTO Orders
                  (order_date, due_date, order_status, customer_id, affiliate_id)
                  VALUES (?, ?, ?, ?, ?)
                  """;
            pst = conn.prepareStatement(sql);
            pst.setDate(1, sqlOrderDate);
            pst.setDate(2, sqlDueDate);
            pst.setString(3, progressStatus);
            pst.setInt(4, customerIDValue);
            
            if (affiliateIDText.isEmpty()) {
                pst.setNull(5, java.sql.Types.VARCHAR);
            } else {
                pst.setString(5, affiliateIDText);
            }
        }
        
        int rowsInserted = pst.executeUpdate();
        if (rowsInserted > 0) {
            JOptionPane.showMessageDialog(this, "Order saved successfully!");
            String finalOrderID = orderIDText;
            
            // If the field was left empty, fetch the newest identity value generated by the DB
            if (finalOrderID.isEmpty()) {
                String getIDSQL = "SELECT MAX(order_id) AS latest_id FROM Orders";
                java.sql.PreparedStatement getIDStmt = conn.prepareStatement(getIDSQL);
                java.sql.ResultSet idRS = getIDStmt.executeQuery();

                if (idRS.next()) {
                    finalOrderID = String.valueOf(idRS.getInt("latest_id"));
                }
                idRS.close();
                getIDStmt.close();
            }
            
            // Reset GUI inputs back to default empty states
            orderID.setText("");
            customerid.setSelectedIndex(-1);
            if (affiliateid.getItemCount() > 0) {
                affiliateid.setSelectedIndex(0); 
            } else {
                affiliateid.setSelectedIndex(-1);
            }

            orderdate.setDate(null);
            duedate.setDate(null);
            progress.clearSelection();

            // Redirect the top-level JFrame container layout to the order items setup layout
            javax.swing.JFrame frame = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
            frame.setContentPane(new editorderitem(finalOrderID));
            frame.revalidate();
            frame.repaint();
        } else {
            JOptionPane.showMessageDialog(this, "Save failed.");
        }
        
        pst.close();
        conn.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Save failed: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_saveActionPerformed

    private void backtotableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backtotableActionPerformed
        javax.swing.JFrame frame =
        (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);

        frame.setContentPane(new order());
        frame.revalidate();
        frame.repaint();            
    }//GEN-LAST:event_backtotableActionPerformed

    private void doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doneActionPerformed

    private void inprogressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inprogressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inprogressActionPerformed

    private void customeridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customeridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customeridActionPerformed

    private void affiliateidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_affiliateidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_affiliateidActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> affiliateid;
    private javax.swing.JButton backtotable;
    private javax.swing.JButton clear;
    private javax.swing.JComboBox<String> customerid;
    private javax.swing.JButton delete;
    private javax.swing.JRadioButton done;
    private com.toedter.calendar.JDateChooser duedate;
    private javax.swing.JRadioButton inprogress;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel mainbg;
    private javax.swing.JRadioButton notstarted;
    private javax.swing.JLabel oID;
    private javax.swing.JLabel oaID;
    private javax.swing.JLabel ocID;
    private javax.swing.JLabel odate;
    private javax.swing.JLabel oduedate;
    private javax.swing.JLabel oprog;
    private javax.swing.JTextField orderID;
    private com.toedter.calendar.JDateChooser orderdate;
    private javax.swing.JLabel producttype;
    private javax.swing.JLabel producttype1;
    private javax.swing.ButtonGroup progress;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
    
    private void loadFonts() {
        try {
            customFont = java.awt.Font.createFont(
                    java.awt.Font.TRUETYPE_FONT,
                    getClass().getResourceAsStream("/ifccrafts/assets/MyFont.ttf")
            );
        } catch (FontFormatException | IOException e) {
            customFont = new java.awt.Font("Serif", java.awt.Font.PLAIN, 18);
        }
    }
}
