
import java.awt.FontFormatException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.ResultSet;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */


/**
 *
 * @author hezekiahmagalona
 */
public class editinventory extends javax.swing.JPanel {
    
    private java.awt.Font customFont;
    private Connection conn;

    /**
     * Creates new form customer
     */
    public editinventory() {
        initComponents();

        try {
            conn = getConnection();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Database connection failed: " + e.getMessage());
            return;
        }
        
        loadFonts();

        if (customFont != null) {
            iID.setFont(customFont.deriveFont(java.awt.Font.BOLD, 28f));
            mat.setFont(customFont.deriveFont(java.awt.Font.BOLD, 28f));
            un.setFont(customFont.deriveFont(java.awt.Font.BOLD, 28f));
            cs.setFont(customFont.deriveFont(java.awt.Font.BOLD, 28f));
        }
        

        generateInventoryId();
    }
    
    private void clearFields() {
        inventoryID.setText("");
        material.setText("");
        unit.setText("");
        mcost.setText("");
        }
    
    private Connection getConnection() throws Exception {
        String url = "jdbc:sqlserver://localhost:1433;"
                + "databaseName=ifcdb;"
                + "encrypt=true;"
                + "trustServerCertificate=true";

        String user = "sa";
        String password = "Anolagam28";

        return DriverManager.getConnection(url, user, password);
    }
    
    private void generateInventoryId() {
    String sql =
            "SELECT ISNULL(MAX(inventory_id), 5999) + 1 AS next_id "
            + "FROM dbo.Inventory";

    try (Connection tempConn = getConnection();
         PreparedStatement pst = tempConn.prepareStatement(sql);
         java.sql.ResultSet rs = pst.executeQuery()) {

        if (rs.next()) {
            inventoryID.setText(String.valueOf(rs.getInt("next_id")));
            inventoryID.setEditable(true);
            inventoryID.setFocusable(true);
        }

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(
                this,
                "Error generating Inventory ID: " + ex.getMessage()
        );
    }
}   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        material = new javax.swing.JTextField();
        unit = new javax.swing.JTextField();
        inventoryID = new javax.swing.JTextField();
        clear = new javax.swing.JButton();
        save = new javax.swing.JButton();
        backtotable = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        mat = new javax.swing.JLabel();
        un = new javax.swing.JLabel();
        iID = new javax.swing.JLabel();
        cs = new javax.swing.JLabel();
        mcost = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        mainbg = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        material.setBackground(new java.awt.Color(255, 255, 255));
        material.setFont(new java.awt.Font("Baskerville", 0, 24)); // NOI18N
        material.setForeground(new java.awt.Color(0, 0, 0));
        material.setBorder(null);
        material.addActionListener(this::materialActionPerformed);
        add(material, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, 370, 50));

        unit.setBackground(new java.awt.Color(255, 255, 255));
        unit.setFont(new java.awt.Font("Baskerville", 0, 24)); // NOI18N
        unit.setForeground(new java.awt.Color(0, 0, 0));
        unit.setBorder(null);
        add(unit, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, 370, 50));

        inventoryID.setBackground(new java.awt.Color(255, 255, 255));
        inventoryID.setFont(new java.awt.Font("Baskerville", 0, 24)); // NOI18N
        inventoryID.setForeground(new java.awt.Color(0, 0, 0));
        inventoryID.setBorder(null);
        add(inventoryID, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 370, 50));

        clear.setBackground(new java.awt.Color(255, 255, 255));
        clear.setFont(new java.awt.Font("Kokonor", 0, 18)); // NOI18N
        clear.setForeground(new java.awt.Color(0, 0, 0));
        clear.setText("Clear");
        clear.addActionListener(this::clearActionPerformed);
        add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 620, 120, 40));

        save.setBackground(new java.awt.Color(255, 255, 255));
        save.setFont(new java.awt.Font("Kokonor", 0, 18)); // NOI18N
        save.setForeground(new java.awt.Color(0, 0, 0));
        save.setText("Save");
        save.addActionListener(this::saveActionPerformed);
        add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 620, 120, 40));

        backtotable.setBackground(new java.awt.Color(255, 255, 255));
        backtotable.setFont(new java.awt.Font("Kokonor", 0, 18)); // NOI18N
        backtotable.setForeground(new java.awt.Color(0, 0, 0));
        backtotable.setText("Back to Table");
        backtotable.setToolTipText("");
        backtotable.addActionListener(this::backtotableActionPerformed);
        add(backtotable, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 620, 150, 40));

        delete.setBackground(new java.awt.Color(255, 255, 255));
        delete.setFont(new java.awt.Font("Kokonor", 0, 18)); // NOI18N
        delete.setForeground(new java.awt.Color(0, 0, 0));
        delete.setText("Delete");
        delete.addActionListener(this::deleteActionPerformed);
        add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 620, 120, 40));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ifccrafts/assets/tfield.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, -1, 70));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ifccrafts/assets/tfield.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 390, -1, 70));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ifccrafts/assets/tfield.png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, -1, 70));

        mat.setFont(new java.awt.Font("Big Caslon", 0, 24)); // NOI18N
        mat.setForeground(new java.awt.Color(255, 255, 255));
        mat.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        mat.setText("Material:");
        add(mat, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 180, 50));

        un.setFont(new java.awt.Font("Big Caslon", 0, 24)); // NOI18N
        un.setForeground(new java.awt.Color(255, 255, 255));
        un.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        un.setText("Unit:");
        add(un, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, 180, 50));

        iID.setFont(new java.awt.Font("Big Caslon", 0, 24)); // NOI18N
        iID.setForeground(new java.awt.Color(255, 255, 255));
        iID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        iID.setText("Inventory ID:");
        add(iID, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 240, 50));

        cs.setFont(new java.awt.Font("Big Caslon", 0, 24)); // NOI18N
        cs.setForeground(new java.awt.Color(255, 255, 255));
        cs.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cs.setText("Material Cost:");
        add(cs, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 500, 260, 50));

        mcost.setBackground(new java.awt.Color(255, 255, 255));
        mcost.setFont(new java.awt.Font("Baskerville", 0, 24)); // NOI18N
        mcost.setForeground(new java.awt.Color(0, 0, 0));
        mcost.setBorder(null);
        add(mcost, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 500, 370, 50));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ifccrafts/assets/tfield.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 490, -1, 70));

        mainbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ifccrafts/assets/mainbg.png"))); // NOI18N
        add(mainbg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void materialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_materialActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        String idText = inventoryID.getText().trim();

    if (idText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Enter Inventory ID first.");
        inventoryID.requestFocus();
        return;
    }

    try {
        int inventoryId = Integer.parseInt(idText);

        try (Connection tempConn = getConnection()) {
            String selectSql =
        "SELECT material, stock_quantity, material_cost "
        + "FROM dbo.Inventory WHERE inventory_id = ?";

            try (PreparedStatement selectPst = tempConn.prepareStatement(selectSql)) {
                selectPst.setInt(1, inventoryId);

                try (ResultSet rs = selectPst.executeQuery()) {
                    if (!rs.next()) {
                        JOptionPane.showMessageDialog(this, "Inventory ID not found.");
                        return;
                    }

                   String message =
                    "Are you sure you want to delete this inventory record?\n\n"
                    + "Inventory ID: " + inventoryId + "\n"
                    + "Material: " + rs.getString("material") + "\n"
                    + "Stock Quantity: " + rs.getInt("stock_quantity") + "\n"
                    + "Material Cost: " + rs.getDouble("material_cost");

                    int confirm = JOptionPane.showConfirmDialog(
                            this,
                            message,
                            "Confirm Delete",
                            JOptionPane.YES_NO_OPTION
                    );

                    if (confirm != JOptionPane.YES_OPTION) {
                        return;
                    }
                }
            }

            String deleteSql = "DELETE FROM dbo.Inventory WHERE inventory_id = ?";

            try (PreparedStatement deletePst = tempConn.prepareStatement(deleteSql)) {
                deletePst.setInt(1, inventoryId);

                int rows = deletePst.executeUpdate();

                if (rows > 0) {
                    JOptionPane.showMessageDialog(this, "Inventory deleted successfully.");
                    clearFields();
                    generateInventoryId();
                } else {
                    JOptionPane.showMessageDialog(this, "Delete failed.");
                }
            }
        }
  

    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Inventory ID must be a number.");
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
    }
    }//GEN-LAST:event_deleteActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        int response = javax.swing.JOptionPane.showConfirmDialog(this,
            "This will clear all your inputs. Continue?",
            "Confirm Clear",
            javax.swing.JOptionPane.YES_NO_OPTION);

        if (response == javax.swing.JOptionPane.YES_OPTION) {
            inventoryID.setText("");
            material.setText("");
            unit.setText("");
            mcost.setText("");
            
            
            javax.swing.JOptionPane.showMessageDialog(this, "Fields cleared successfully.");}
    }//GEN-LAST:event_clearActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        String materialName = material.getText().trim();
        String stockText = unit.getText().trim();
        String costText = mcost.getText().trim();

        if (materialName.isEmpty() || stockText.isEmpty() || costText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields.");
            return;
        }

        try {
            int stockQuantity = Integer.parseInt(stockText);
            double materialCost = Double.parseDouble(costText);

            if (stockQuantity < 0 || materialCost < 0) {
                JOptionPane.showMessageDialog(this, "Stock quantity and material cost cannot be negative.");
                return;
            }

            String message =
                    "Are you sure you want to save this inventory record?\n\n"
                    + "Material: " + materialName + "\n"
                    + "Stock Quantity: " + stockQuantity + "\n"
                    + "Material Cost: " + materialCost;

            int confirm = JOptionPane.showConfirmDialog(
                    this,
                    message,
                    "Confirm Save",
                    JOptionPane.YES_NO_OPTION
            );

            if (confirm != JOptionPane.YES_OPTION) {
                return;
            }

            String sql =
                    "INSERT INTO dbo.Inventory "
                    + "(material, stock_quantity, material_cost) "
                    + "VALUES (?, ?, ?)";

            try (Connection tempConn = getConnection();
                 PreparedStatement pst = tempConn.prepareStatement(sql)) {

                pst.setString(1, materialName);
                pst.setInt(2, stockQuantity);
                pst.setDouble(3, materialCost);

                pst.executeUpdate();
            }

            JOptionPane.showMessageDialog(this, "Inventory saved successfully.");
            clearFields();
            generateInventoryId();

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Stock quantity must be a whole number and material cost must be a number.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_saveActionPerformed

    private void backtotableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backtotableActionPerformed
        javax.swing.JFrame frame =
        (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);

        frame.setContentPane(new inventory());
        frame.revalidate();
        frame.repaint();            
    }//GEN-LAST:event_backtotableActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backtotable;
    private javax.swing.JButton clear;
    private javax.swing.JLabel cs;
    private javax.swing.JButton delete;
    private javax.swing.JLabel iID;
    private javax.swing.JTextField inventoryID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel mainbg;
    private javax.swing.JLabel mat;
    private javax.swing.JTextField material;
    private javax.swing.JTextField mcost;
    private javax.swing.JButton save;
    private javax.swing.JLabel un;
    private javax.swing.JTextField unit;
    // End of variables declaration//GEN-END:variables
    
    private void loadFonts() {
        try {
            customFont = java.awt.Font.createFont(
                    java.awt.Font.TRUETYPE_FONT,
                    getClass().getResourceAsStream("/ifccrafts/assets/MyFont.ttf")
            );
        } catch (FontFormatException | IOException e) {
            customFont = new java.awt.Font("Serif", java.awt.Font.PLAIN, 18);
        }
    }
}
