import java.awt.CardLayout;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.awt.FontFormatException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JPanel;
import java.sql.PreparedStatement;
import java.sql.Date;
import java.sql.ResultSet;
import com.toedter.calendar.JDateChooser;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */


/**
 *
 * @author hezekiahmagalona
 */
public class editaffiliate extends javax.swing.JPanel {
    
    private java.awt.Font customFont;
    private Connection conn;
    private JPanel container; 
    private CardLayout layout;


    /**
     * Creates new form customer
     */
    public editaffiliate() {
        initComponents();

        affiliatestatus.setUI(new javax.swing.plaf.basic.BasicComboBoxUI());
        affiliatestatus.setBackground(java.awt.Color.WHITE);
        affiliatestatus.setForeground(java.awt.Color.BLACK);

        loadFonts();

        aID.setFont(customFont.deriveFont(java.awt.Font.BOLD, 28f));
        affname.setFont(customFont.deriveFont(java.awt.Font.BOLD, 28f));
        startd.setFont(customFont.deriveFont(java.awt.Font.BOLD, 28f));
        endd.setFont(customFont.deriveFont(java.awt.Font.BOLD, 28f));
        affstat.setFont(customFont.deriveFont(java.awt.Font.BOLD, 28f));
        sma.setFont(customFont.deriveFont(java.awt.Font.BOLD, 28f));

        try {
            conn = getConnection();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Database connection failed: " + e.getMessage());
        }

        // format and display affiliate ID as name updates
        afiliatename.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) { updateID(); }
            @Override
            public void removeUpdate(DocumentEvent e) { updateID(); }
            @Override
            public void changedUpdate(DocumentEvent e) { updateID(); }

            private void updateID() {
                String nameText = afiliatename.getText().trim().replaceAll("\\s+", "").toLowerCase();
                if (!nameText.isEmpty()) {
                    affiliateID.setText(nameText + "Xifc");
                } else {
                    affiliateID.setText("");
                }
            }
        });
    }
    

    private Connection getConnection() throws Exception {
        String url = "jdbc:sqlserver://localhost:1433;"
                + "databaseName=ifcdb;"
                + "encrypt=true;"
                + "trustServerCertificate=true";

        String user = "sa";
        String password = "Anolagam28";

        return java.sql.DriverManager.getConnection(url, user, password);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enddate = new com.toedter.calendar.JDateChooser();
        startdate = new com.toedter.calendar.JDateChooser();
        affiliatestatus = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        afiliatename = new javax.swing.JTextField();
        socmedacc = new javax.swing.JTextField();
        affiliateID = new javax.swing.JTextField();
        clear = new javax.swing.JButton();
        save = new javax.swing.JButton();
        backtotable = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pel4 = new javax.swing.JLabel();
        affname = new javax.swing.JLabel();
        startd = new javax.swing.JLabel();
        affstat = new javax.swing.JLabel();
        sma = new javax.swing.JLabel();
        endd = new javax.swing.JLabel();
        aID = new javax.swing.JLabel();
        mainbg = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enddate.setBackground(new java.awt.Color(255, 255, 255));
        enddate.setForeground(new java.awt.Color(0, 0, 0));
        enddate.setFont(new java.awt.Font("Kokonor", 0, 24)); // NOI18N
        enddate.setOpaque(false);
        add(enddate, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, 370, 50));

        startdate.setBackground(new java.awt.Color(255, 255, 255));
        startdate.setForeground(new java.awt.Color(0, 0, 0));
        startdate.setFont(new java.awt.Font("Kokonor", 0, 24)); // NOI18N
        startdate.setOpaque(false);
        add(startdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, 370, 50));

        affiliatestatus.setBackground(new java.awt.Color(255, 255, 255));
        affiliatestatus.setFont(new java.awt.Font("Kokonor", 0, 24)); // NOI18N
        affiliatestatus.setForeground(new java.awt.Color(0, 0, 0));
        affiliatestatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Inactive", "Expired" }));
        affiliatestatus.setSelectedIndex(-1);
        affiliatestatus.setPreferredSize(new java.awt.Dimension(133, 65));
        affiliatestatus.addActionListener(this::affiliatestatusActionPerformed);
        add(affiliatestatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 480, 380, 50));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ifccrafts/assets/tfield.png"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 470, -1, 70));

        afiliatename.setBackground(new java.awt.Color(255, 255, 255));
        afiliatename.setFont(new java.awt.Font("Baskerville", 0, 24)); // NOI18N
        afiliatename.setForeground(new java.awt.Color(0, 0, 0));
        afiliatename.setBorder(null);
        afiliatename.addActionListener(this::afiliatenameActionPerformed);
        add(afiliatename, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 370, 50));

        socmedacc.setBackground(new java.awt.Color(255, 255, 255));
        socmedacc.setFont(new java.awt.Font("Baskerville", 0, 24)); // NOI18N
        socmedacc.setForeground(new java.awt.Color(0, 0, 0));
        socmedacc.setBorder(null);
        add(socmedacc, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 560, 370, 50));

        affiliateID.setBackground(new java.awt.Color(255, 255, 255));
        affiliateID.setFont(new java.awt.Font("Baskerville", 0, 24)); // NOI18N
        affiliateID.setForeground(new java.awt.Color(0, 0, 0));
        affiliateID.setBorder(null);
        add(affiliateID, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, 370, 50));

        clear.setBackground(new java.awt.Color(255, 255, 255));
        clear.setFont(new java.awt.Font("Kokonor", 0, 18)); // NOI18N
        clear.setForeground(new java.awt.Color(0, 0, 0));
        clear.setText("Clear");
        clear.addActionListener(this::clearActionPerformed);
        add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 670, 120, 40));

        save.setBackground(new java.awt.Color(255, 255, 255));
        save.setFont(new java.awt.Font("Kokonor", 0, 18)); // NOI18N
        save.setForeground(new java.awt.Color(0, 0, 0));
        save.setText("Save");
        save.addActionListener(this::saveActionPerformed);
        add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 670, 120, 40));

        backtotable.setBackground(new java.awt.Color(255, 255, 255));
        backtotable.setFont(new java.awt.Font("Kokonor", 0, 18)); // NOI18N
        backtotable.setForeground(new java.awt.Color(0, 0, 0));
        backtotable.setText("Back to Table");
        backtotable.setToolTipText("");
        backtotable.addActionListener(this::backtotableActionPerformed);
        add(backtotable, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 670, 150, 40));

        delete.setBackground(new java.awt.Color(255, 255, 255));
        delete.setFont(new java.awt.Font("Kokonor", 0, 18)); // NOI18N
        delete.setForeground(new java.awt.Color(0, 0, 0));
        delete.setText("Delete");
        delete.addActionListener(this::deleteActionPerformed);
        add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 670, 120, 40));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ifccrafts/assets/tfield.png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, -1, 70));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ifccrafts/assets/tfield.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, -1, 70));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ifccrafts/assets/tfield.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 390, -1, 70));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ifccrafts/assets/tfield.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 550, -1, 70));

        pel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ifccrafts/assets/tfield.png"))); // NOI18N
        add(pel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, -1, 70));

        affname.setFont(new java.awt.Font("Big Caslon", 0, 24)); // NOI18N
        affname.setForeground(new java.awt.Color(255, 255, 255));
        affname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        affname.setText("Affiliate Name:");
        add(affname, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 230, 50));

        startd.setFont(new java.awt.Font("Big Caslon", 0, 24)); // NOI18N
        startd.setForeground(new java.awt.Color(255, 255, 255));
        startd.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        startd.setText("Start Date:");
        add(startd, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 220, 50));

        affstat.setFont(new java.awt.Font("Big Caslon", 0, 24)); // NOI18N
        affstat.setForeground(new java.awt.Color(255, 255, 255));
        affstat.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        affstat.setText("Affiliate Status:");
        add(affstat, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 480, 240, 50));

        sma.setFont(new java.awt.Font("Big Caslon", 0, 24)); // NOI18N
        sma.setForeground(new java.awt.Color(255, 255, 255));
        sma.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        sma.setText("Social Media Account:");
        add(sma, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 560, 320, 50));

        endd.setFont(new java.awt.Font("Big Caslon", 0, 24)); // NOI18N
        endd.setForeground(new java.awt.Color(255, 255, 255));
        endd.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        endd.setText("End Date:");
        add(endd, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 240, 50));

        aID.setFont(new java.awt.Font("Big Caslon", 0, 24)); // NOI18N
        aID.setForeground(new java.awt.Color(255, 255, 255));
        aID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        aID.setText("Affiliate ID:");
        add(aID, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 170, 50));

        mainbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ifccrafts/assets/mainbg.png"))); // NOI18N
        add(mainbg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, -1));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ifccrafts/assets/tfield.png"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, -1, 70));
    }// </editor-fold>//GEN-END:initComponents

    private void afiliatenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afiliatenameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_afiliatenameActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        String affiliateId = affiliateID.getText().trim();

        if (affiliateId.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter Affiliate ID to delete.");
            return;
        }

        try {
            // DETAILS RECORD
            String sql = "SELECT * FROM Affiliates WHERE affiliate_id = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, affiliateId);

            ResultSet rs = pst.executeQuery();

            if (!rs.next()) {
                JOptionPane.showMessageDialog(this, "Affiliate ID not found.");
                return;
            }

            String name = rs.getString("aff_name");
            Date start = rs.getDate("start_date");
            Date end = rs.getDate("end_date");
            String status = rs.getString("aff_status");
            String social = rs.getString("soc_med_acc");

            // PREVIEW DIALOUGE 
            String message = "Are you sure to delete this record?:\n\n"
                    + "ID: " + affiliateId + "\n"
                    + "Name: " + name + "\n"
                    + "Start Date: " + start + "\n"
                    + "End Date: " + end + "\n"
                    + "Status: " + status + "\n"
                    + "Social Media: " + social + "\n\n"
                    + "Are you sure you want to delete this?";

            int confirm = JOptionPane.showConfirmDialog(
                    this,
                    message,
                    "Confirm Delete",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE
            );

            if (confirm != JOptionPane.YES_OPTION) {
                return;
            }

            String deleteSql = "DELETE FROM Affiliates WHERE affiliate_id = ?";
            PreparedStatement deletePst = conn.prepareStatement(deleteSql);
            deletePst.setString(1, affiliateId);

            int rows = deletePst.executeUpdate();

            if (rows > 0) {
                JOptionPane.showMessageDialog(this, "Affiliate deleted successfully!");
            } else {
                JOptionPane.showMessageDialog(this, "Delete failed.");
            }

            deletePst.close();

            affiliateID.setText("");
            afiliatename.setText("");
            startdate.setDate(null);
            enddate.setDate(null);
            affiliatestatus.setSelectedIndex(-1);
            socmedacc.setText("");

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Database Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
         int response = javax.swing.JOptionPane.showConfirmDialog(this,
            "This will clear all your inputs. Continue?",
            "Confirm Clear",
            javax.swing.JOptionPane.YES_NO_OPTION);

        if (response == javax.swing.JOptionPane.YES_OPTION) {
            affiliateID.setText("");
            afiliatename.setText("");
            startdate.setDate(null);
            enddate.setDate(null);
            affiliatestatus.setSelectedIndex(-1);
            socmedacc.setText("");
            
            javax.swing.JOptionPane.showMessageDialog(this, "Fields cleared successfully.");}
    }//GEN-LAST:event_clearActionPerformed

    
    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        String affiliateId = affiliateID.getText().trim();
        String affiliateName = afiliatename.getText().trim();
        String status = affiliatestatus.getSelectedItem() != null 
                        ? affiliatestatus.getSelectedItem().toString() 
                        : "";
        String socialMedia = socmedacc.getText().trim();

        java.util.Date startUtilDate = startdate.getDate();
        java.util.Date endUtilDate = enddate.getDate();

        if (affiliateId.isEmpty() || affiliateName.isEmpty() || 
            startUtilDate == null || endUtilDate == null || 
            status.isEmpty() || socialMedia.isEmpty()) {

            JOptionPane.showMessageDialog(this, "Please fill in all fields.");
            return;
        }

        java.sql.Date startDate = new java.sql.Date(startUtilDate.getTime());
        java.sql.Date endDate = new java.sql.Date(endUtilDate.getTime());

        // UPDATED: Active state check rule processing
        java.sql.Date today = new java.sql.Date(System.currentTimeMillis());
        if (endDate.getTime() < today.getTime()) {
            status = "Expired";
        } else {
            status = "Active";
        }

        String message = "Save this affiliate?\n\n"
                + "ID: " + affiliateId + "\n"
                + "Name: " + affiliateName + "\n"
                + "Start Date: " + startDate + "\n"
                + "End Date: " + endDate + "\n"
                + "Status: " + status + "\n"
                + "Social Media: " + socialMedia;

        int confirm = JOptionPane.showConfirmDialog(
                this,
                message,
                "Confirm Save",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        try {
            String sql = "INSERT INTO Affiliates "
                    + "(affiliate_id, aff_name, start_date, end_date, aff_status, soc_med_acc) "
                    + "VALUES (?, ?, ?, ?, ?, ?)";

            PreparedStatement pst = conn.prepareStatement(sql);

            pst.setString(1, affiliateId);
            pst.setString(2, affiliateName);
            pst.setDate(3, startDate);
            pst.setDate(4, endDate);
            pst.setString(5, status);
            pst.setString(6, socialMedia);

            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Affiliate saved successfully!");
            pst.close();
            clearFields();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Database Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_saveActionPerformed

    private void clearFields() {
        affiliateID.setText("");
        afiliatename.setText("");
        startdate.setDate(null);
        enddate.setDate(null);
        affiliatestatus.setSelectedIndex(-1);
        socmedacc.setText("");
    }
    
    private void backtotableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backtotableActionPerformed
        javax.swing.JFrame frame =
        (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);

        frame.setContentPane(new affiliate());
        frame.revalidate();
        frame.repaint();            
    }//GEN-LAST:event_backtotableActionPerformed

    private void affiliatestatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_affiliatestatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_affiliatestatusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aID;
    private javax.swing.JTextField affiliateID;
    private javax.swing.JComboBox<String> affiliatestatus;
    private javax.swing.JLabel affname;
    private javax.swing.JLabel affstat;
    private javax.swing.JTextField afiliatename;
    private javax.swing.JButton backtotable;
    private javax.swing.JButton clear;
    private javax.swing.JButton delete;
    private javax.swing.JLabel endd;
    private com.toedter.calendar.JDateChooser enddate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel mainbg;
    private javax.swing.JLabel pel4;
    private javax.swing.JButton save;
    private javax.swing.JLabel sma;
    private javax.swing.JTextField socmedacc;
    private javax.swing.JLabel startd;
    private com.toedter.calendar.JDateChooser startdate;
    // End of variables declaration//GEN-END:variables
    
    private void loadFonts() {
        try {
            customFont = java.awt.Font.createFont(
                    java.awt.Font.TRUETYPE_FONT,
                    getClass().getResourceAsStream("/ifccrafts/assets/MyFont.ttf")
            );
        } catch (FontFormatException | IOException e) {
            customFont = new java.awt.Font("Serif", java.awt.Font.PLAIN, 18);
        }
    }
}
