import java.awt.FontFormatException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */


/**
 *
 * @author hezekiahmagalona
 */
public class editorderitem extends javax.swing.JPanel {
    
    private java.awt.Font customFont;


    /**
     * Creates new form customer
     */
    public editorderitem() {
        initComponents();
        loadFonts();
        loadProductIDs();
        
        productname.setUI(new javax.swing.plaf.basic.BasicComboBoxUI());
        productname.setBackground(java.awt.Color.WHITE);
        productname.setForeground(java.awt.Color.BLACK);


        if (customFont != null) {
            oID.setFont(customFont.deriveFont(java.awt.Font.BOLD, 28f));
            opid.setFont(customFont.deriveFont(java.awt.Font.BOLD, 28f));
            qua.setFont(customFont.deriveFont(java.awt.Font.BOLD, 28f));
            priceao.setFont(customFont.deriveFont(java.awt.Font.BOLD, 28f));
        }
        
        productID.setEditable(true);
        priceatorder.setEditable(true);
        
        productname.addActionListener(e -> fetchProductDetails());
    }
    
    public editorderitem(String orderID) {
        this(); 

        orderD.setText(orderID);
    }
    
    private void fetchProductDetails() {
        Object selected = productname.getSelectedItem();

        if (selected == null || selected.toString().trim().isEmpty()) {
            productID.setText("");
            priceatorder.setText("");
            return;
        }

        String selectedName = selected.toString().trim();

        String query = "SELECT product_id, unit_price FROM Products WHERE product_name = ?";
        try (Connection conn = getConnection();
             PreparedStatement pst = conn.prepareStatement(query)) {
            
            pst.setString(1, selectedName);
            try (ResultSet rs = pst.executeQuery()) {
                if (rs.next()) {
                    int id = rs.getInt("product_id");
                    double price = rs.getDouble("unit_price");
                    
                    productID.setText(String.valueOf(id));
                    priceatorder.setText(String.format("%.2f", price)); 
                } else {
                    productID.setText("Not Found");
                    priceatorder.setText("Not Found");
                }
            }
        } catch (Exception e) {
            productID.setText("Error");
            priceatorder.setText("Error");
        }
    }
    
  
    
    private void loadProductIDs() {
    try (Connection conn = getConnection();
             PreparedStatement pst = conn.prepareStatement("SELECT product_name FROM Products ORDER BY product_name");
             ResultSet rs = pst.executeQuery()) {

            productname.removeAllItems();
            productname.addItem("");

            while (rs.next()) {
                productname.addItem(rs.getString("product_name"));
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Failed to load product names: " + e.getMessage()
            );
        }
}
    
    
    private Connection getConnection() throws Exception {
        String url = "jdbc:sqlserver://localhost:1433;"
                + "databaseName=ifcdb;"
                + "encrypt=true;"
                + "trustServerCertificate=true";

        String user = "sa";
        String password = "Anolagam28";

        return java.sql.DriverManager.getConnection(url, user, password);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productname = new javax.swing.JComboBox<>();
        productID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        oID1 = new javax.swing.JLabel();
        quantity = new javax.swing.JTextField();
        priceatorder = new javax.swing.JTextField();
        orderD = new javax.swing.JTextField();
        clear = new javax.swing.JButton();
        save = new javax.swing.JButton();
        backtotable = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        opid = new javax.swing.JLabel();
        qua = new javax.swing.JLabel();
        priceao = new javax.swing.JLabel();
        oID = new javax.swing.JLabel();
        mainbg = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        productname.setBackground(new java.awt.Color(255, 255, 255));
        productname.setFont(new java.awt.Font("Kokonor", 0, 24)); // NOI18N
        productname.setForeground(new java.awt.Color(0, 0, 0));
        productname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Inactive", "Expired" }));
        productname.setSelectedIndex(-1);
        productname.setPreferredSize(new java.awt.Dimension(133, 65));
        productname.addActionListener(this::productnameActionPerformed);
        add(productname, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 380, 50));

        productID.setBackground(new java.awt.Color(255, 255, 255));
        productID.setFont(new java.awt.Font("Baskerville", 0, 24)); // NOI18N
        productID.setForeground(new java.awt.Color(0, 0, 0));
        productID.setBorder(null);
        add(productID, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 370, 50));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ifccrafts/assets/tfield.png"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, -1, 70));

        oID1.setFont(new java.awt.Font("Big Caslon", 0, 24)); // NOI18N
        oID1.setForeground(new java.awt.Color(255, 255, 255));
        oID1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        oID1.setText("Product Name:");
        add(oID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 210, 50));

        quantity.setBackground(new java.awt.Color(255, 255, 255));
        quantity.setFont(new java.awt.Font("Baskerville", 0, 24)); // NOI18N
        quantity.setForeground(new java.awt.Color(0, 0, 0));
        quantity.setBorder(null);
        add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, 370, 50));

        priceatorder.setBackground(new java.awt.Color(255, 255, 255));
        priceatorder.setFont(new java.awt.Font("Baskerville", 0, 24)); // NOI18N
        priceatorder.setForeground(new java.awt.Color(0, 0, 0));
        priceatorder.setBorder(null);
        add(priceatorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 500, 370, 50));

        orderD.setBackground(new java.awt.Color(255, 255, 255));
        orderD.setFont(new java.awt.Font("Baskerville", 0, 24)); // NOI18N
        orderD.setForeground(new java.awt.Color(0, 0, 0));
        orderD.setBorder(null);
        add(orderD, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, 370, 50));

        clear.setBackground(new java.awt.Color(255, 255, 255));
        clear.setFont(new java.awt.Font("Kokonor", 0, 18)); // NOI18N
        clear.setForeground(new java.awt.Color(0, 0, 0));
        clear.setText("Clear");
        clear.addActionListener(this::clearActionPerformed);
        add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 640, 120, 40));

        save.setBackground(new java.awt.Color(255, 255, 255));
        save.setFont(new java.awt.Font("Kokonor", 0, 18)); // NOI18N
        save.setForeground(new java.awt.Color(0, 0, 0));
        save.setText("Save");
        save.addActionListener(this::saveActionPerformed);
        add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 640, 120, 40));

        backtotable.setBackground(new java.awt.Color(255, 255, 255));
        backtotable.setFont(new java.awt.Font("Kokonor", 0, 18)); // NOI18N
        backtotable.setForeground(new java.awt.Color(0, 0, 0));
        backtotable.setText("Back to Table");
        backtotable.setToolTipText("");
        backtotable.addActionListener(this::backtotableActionPerformed);
        add(backtotable, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 640, 150, 40));

        delete.setBackground(new java.awt.Color(255, 255, 255));
        delete.setFont(new java.awt.Font("Kokonor", 0, 18)); // NOI18N
        delete.setForeground(new java.awt.Color(0, 0, 0));
        delete.setText("Delete");
        delete.addActionListener(this::deleteActionPerformed);
        add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 640, 120, 40));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ifccrafts/assets/tfield.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, -1, 70));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ifccrafts/assets/tfield.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 400, -1, 70));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ifccrafts/assets/tfield.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 490, -1, 70));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ifccrafts/assets/tfield.png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, -1, 70));

        opid.setFont(new java.awt.Font("Big Caslon", 0, 24)); // NOI18N
        opid.setForeground(new java.awt.Color(255, 255, 255));
        opid.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        opid.setText("Product ID:");
        add(opid, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 180, 50));

        qua.setFont(new java.awt.Font("Big Caslon", 0, 24)); // NOI18N
        qua.setForeground(new java.awt.Color(255, 255, 255));
        qua.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        qua.setText("Quantity:");
        add(qua, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 180, 50));

        priceao.setFont(new java.awt.Font("Big Caslon", 0, 24)); // NOI18N
        priceao.setForeground(new java.awt.Color(255, 255, 255));
        priceao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        priceao.setText("Price at Order:");
        add(priceao, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 500, 240, 50));

        oID.setFont(new java.awt.Font("Big Caslon", 0, 24)); // NOI18N
        oID.setForeground(new java.awt.Color(255, 255, 255));
        oID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        oID.setText("Order ID:");
        add(oID, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 170, 50));

        mainbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ifccrafts/assets/mainbg.png"))); // NOI18N
        add(mainbg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        try {
            String orderIDText = orderD.getText().trim();
            String productIDText = productID.getText().trim();
            
            if (orderIDText.isEmpty() || productIDText.isEmpty() || productIDText.equals("Not Found") || productIDText.equals("Error")) {
                JOptionPane.showMessageDialog(this, "Valid Order ID and chosen Product Name are required to extract Product ID.");
                return;
            }
            
            if (!quantity.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Only Order ID and Product Name should be valid when deleting.");
                return;
            }

            int orderIDValue;
            try {
                String cleanOID = orderIDText.replaceAll("[^0-9]", "");
                orderIDValue = Integer.parseInt(cleanOID);
                if (orderIDValue < 3000) {
                    JOptionPane.showMessageDialog(this, "Order ID must be 3000 or higher.");
                    return;
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Order ID must be a valid number.");
                return;
            }

            int productIDValue;
            try {
                String cleanPID = productIDText.replaceAll("[^0-9]", "");
                productIDValue = Integer.parseInt(cleanPID);
                if (productIDValue < 2000 || productIDValue > 2999) {
                    JOptionPane.showMessageDialog(this, "Product ID must be from 2000 to 2999.");
                    return;
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Invalid Product ID derived from chosen Product.");
                return;
            }

            try (java.sql.Connection conn = getConnection()) {
                String checkSQL = "SELECT * FROM Order_Items WHERE order_id = ? AND product_id = ?";
                try (java.sql.PreparedStatement checkStmt = conn.prepareStatement(checkSQL)) {
                    checkStmt.setInt(1, orderIDValue);
                    checkStmt.setInt(2, productIDValue);

                    try (java.sql.ResultSet rs = checkStmt.executeQuery()) {
                        if (!rs.next()) {
                            JOptionPane.showMessageDialog(this, "Order Item record does not exist.");
                            return;
                        }

                        int qty = rs.getInt("quantity");
                        double priceAtOrder = rs.getDouble("price_at_order");

                        String message = "Are you sure you want to delete this information?\n\n"
                                + "Order ID: " + orderIDValue + "\n"
                                + "Product ID: " + productIDValue + "\n"
                                + "Quantity: " + qty + "\n"
                                + "Price at Order: " + priceAtOrder;

                        int confirm = JOptionPane.showConfirmDialog(
                                this, message, "Confirm Delete", JOptionPane.YES_NO_OPTION
                        );

                        if (confirm != JOptionPane.YES_OPTION) {
                            return;
                        }
                    }
                }

                String deleteSQL = "DELETE FROM Order_Items WHERE order_id = ? AND product_id = ?";
                try (java.sql.PreparedStatement deleteStmt = conn.prepareStatement(deleteSQL)) {
                    deleteStmt.setInt(1, orderIDValue);
                    deleteStmt.setInt(2, productIDValue);

                    int rowsDeleted = deleteStmt.executeUpdate();
                    if (rowsDeleted > 0) {
                        JOptionPane.showMessageDialog(this, "Order Item deleted successfully!");
                        clearActionPerformed(null);
                    } else {
                        JOptionPane.showMessageDialog(this, "Delete failed.");
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        int response = javax.swing.JOptionPane.showConfirmDialog(this,
            "This will clear all your inputs. Continue?",
            "Confirm Clear",
            javax.swing.JOptionPane.YES_NO_OPTION);

        if (response == javax.swing.JOptionPane.YES_OPTION) {
            orderD.setText("");
            if (productname.getItemCount() > 0) {
                productname.setSelectedIndex(0); // blank option if you added ""
            } else {
                productname.setSelectedIndex(-1);
            }
            quantity.setText("");
            
            javax.swing.JOptionPane.showMessageDialog(this, "Fields cleared successfully.");}
    }//GEN-LAST:event_clearActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        try {
            String orderIDText = orderD.getText().trim();
            String quantityText = quantity.getText().trim();
            String productIDText = productID.getText().trim();
            String priceText = priceatorder.getText().trim();

            Object selected = productname.getSelectedItem();

            if (orderIDText.isEmpty()
                    || selected == null
                    || selected.toString().trim().isEmpty()
                    || quantityText.isEmpty()
                    || productIDText.isEmpty()
                    || priceText.isEmpty()) {

                JOptionPane.showMessageDialog(this, "Please fill in all required fields.");
                return;
            }

            int orderIDValue;
            try {
                String cleanOID = orderIDText.replaceAll("[^0-9]", "");
                orderIDValue = Integer.parseInt(cleanOID);
                if (orderIDValue < 3000) {
                    JOptionPane.showMessageDialog(this, "Order ID must be 3000 or above.");
                    return;
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Order ID must be a valid number.");
                return;
            }

            int productIDValue;
            try {
                String cleanPID = productIDText.replaceAll("[^0-9]", "");
                productIDValue = Integer.parseInt(cleanPID);
                if (productIDValue < 2000 || productIDValue > 2999) {
                    JOptionPane.showMessageDialog(this, "Product ID must be between 2000 and 2999.");
                    return;
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Product ID must be a valid number.");
                return;
            }

            int quantityValue;
            try {
                String cleanQty = quantityText.replaceAll("[^0-9]", "");
                quantityValue = Integer.parseInt(cleanQty);
                if (quantityValue <= 0) {
                    JOptionPane.showMessageDialog(this, "Quantity must be greater than 0.");
                    return;
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Quantity must be a valid number.");
                return;
            }

            double priceValue;
            try {
                String cleanPrice = priceText.replaceAll("[^0-9.]", "");
                priceValue = Double.parseDouble(cleanPrice);
                if (priceValue < 0) {
                    JOptionPane.showMessageDialog(this, "Price at Order cannot be negative.");
                    return;
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Price at Order must be a valid decimal number.");
                return;
            }

            try (Connection conn = getConnection()) {
                String checkOrderSQL = "SELECT * FROM Orders WHERE order_id = ?";
                try (PreparedStatement checkOrder = conn.prepareStatement(checkOrderSQL)) {
                    checkOrder.setInt(1, orderIDValue);
                    try (ResultSet orderRS = checkOrder.executeQuery()) {
                        if (!orderRS.next()) {
                            JOptionPane.showMessageDialog(this, "Order ID does not exist.");
                            return;
                        }
                    }
                }

                String checkProductSQL = "SELECT * FROM Products WHERE product_id = ?";
                try (PreparedStatement checkProduct = conn.prepareStatement(checkProductSQL)) {
                    checkProduct.setInt(1, productIDValue);
                    try (ResultSet productRS = checkProduct.executeQuery()) {
                        if (!productRS.next()) {
                            JOptionPane.showMessageDialog(this, "Product derived does not exist inside Products master table.");
                            return;
                        }
                    }
                }

                String duplicateSQL = "SELECT * FROM Order_Items WHERE order_id = ? AND product_id = ?";
                try (PreparedStatement duplicateStmt = conn.prepareStatement(duplicateSQL)) {
                    duplicateStmt.setInt(1, orderIDValue);
                    duplicateStmt.setInt(2, productIDValue);
                    try (ResultSet duplicateRS = duplicateStmt.executeQuery()) {
                        if (duplicateRS.next()) {
                            JOptionPane.showMessageDialog(this, "This Order Item record already exists.");
                            return;
                        }
                    }
                }

                String summary = "Are you sure you want to save this?\n\n"
                        + "Order ID: " + orderIDValue + "\n"
                        + "Product ID: " + productIDValue + " (" + selected.toString().trim() + ")\n"
                        + "Quantity: " + quantityValue + "\n"
                        + "Price at Order: " + String.format("%.2f", priceValue);

                int confirm = JOptionPane.showConfirmDialog(
                        this, summary, "Confirm Save", JOptionPane.YES_NO_OPTION
                );

                if (confirm != JOptionPane.YES_OPTION) {
                    return;
                }

                String insertSQL = "INSERT INTO Order_Items (order_id, product_id, quantity, price_at_order) VALUES (?, ?, ?, ?)";
                try (PreparedStatement pst = conn.prepareStatement(insertSQL)) {
                    pst.setInt(1, orderIDValue);
                    pst.setInt(2, productIDValue);
                    pst.setInt(3, quantityValue);
                    pst.setDouble(4, priceValue);

                    int rowsInserted = pst.executeUpdate();

                    if (rowsInserted > 0) {
                        JOptionPane.showMessageDialog(this, "Order Item saved successfully!");

                        int choice = JOptionPane.showConfirmDialog(
                                this,
                                "Will you save another record with Order ID " + orderIDValue + "?",
                                "Add Another Item",
                                JOptionPane.YES_NO_OPTION
                        );

                        if (choice == JOptionPane.YES_OPTION) {
                            productname.setSelectedIndex(0);
                            productID.setText("");
                            quantity.setText("");
                            priceatorder.setText("");
                            productname.requestFocus();
                        } else {
                            javax.swing.JFrame frame = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
                            frame.setContentPane(new edittransaction(String.valueOf(orderIDValue)));
                            frame.revalidate();
                            frame.repaint();
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Save failed.");
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Save failed: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_saveActionPerformed

    private void backtotableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backtotableActionPerformed
        javax.swing.JFrame frame =
        (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);

        orderitem orderItemPage = new orderitem();
        frame.setContentPane(orderItemPage);

        orderItemPage.revalidate();
        orderItemPage.repaint();      
    }//GEN-LAST:event_backtotableActionPerformed

    private void productnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productnameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backtotable;
    private javax.swing.JButton clear;
    private javax.swing.JButton delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel mainbg;
    private javax.swing.JLabel oID;
    private javax.swing.JLabel oID1;
    private javax.swing.JLabel opid;
    private javax.swing.JTextField orderD;
    private javax.swing.JLabel priceao;
    private javax.swing.JTextField priceatorder;
    private javax.swing.JTextField productID;
    private javax.swing.JComboBox<String> productname;
    private javax.swing.JLabel qua;
    private javax.swing.JTextField quantity;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
    
    private void loadFonts() {
        try {
            customFont = java.awt.Font.createFont(
                    java.awt.Font.TRUETYPE_FONT,
                    getClass().getResourceAsStream("/ifccrafts/assets/MyFont.ttf")
            );
        } catch (FontFormatException | IOException e) {
            customFont = new java.awt.Font("Serif", java.awt.Font.PLAIN, 18);
        }
    }
}
