/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author hezekiahmagalona
 */
public class homepage extends javax.swing.JPanel {

    private java.awt.CardLayout layout;
    private javax.swing.JPanel container;

    /**
     *
     * Creates new form homepage1
     */
    public homepage() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btncustomer = new javax.swing.JButton();
        btnproduct = new javax.swing.JButton();
        btnorder = new javax.swing.JButton();
        btninventory = new javax.swing.JButton();
        btnshipment = new javax.swing.JButton();
        btnaffiliate = new javax.swing.JButton();
        btndashboard = new javax.swing.JButton();
        btntransaction = new javax.swing.JButton();
        back = new javax.swing.JButton();
        mainbg = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btncustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ifccrafts/assets/customer.png"))); // NOI18N
        btncustomer.setBorderPainted(false);
        btncustomer.setContentAreaFilled(false);
        btncustomer.setFocusPainted(false);
        btncustomer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btncustomer.addActionListener(this::btncustomerActionPerformed);
        add(btncustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 200, 190));

        btnproduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ifccrafts/assets/product.png"))); // NOI18N
        btnproduct.setBorderPainted(false);
        btnproduct.setContentAreaFilled(false);
        btnproduct.setFocusPainted(false);
        btnproduct.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnproduct.addActionListener(this::btnproductActionPerformed);
        add(btnproduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 200, 190));

        btnorder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ifccrafts/assets/order.png"))); // NOI18N
        btnorder.setBorderPainted(false);
        btnorder.setContentAreaFilled(false);
        btnorder.setFocusPainted(false);
        btnorder.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnorder.addActionListener(this::btnorderActionPerformed);
        add(btnorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 210, 200, 190));

        btninventory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ifccrafts/assets/inventory.png"))); // NOI18N
        btninventory.setBorderPainted(false);
        btninventory.setContentAreaFilled(false);
        btninventory.setFocusPainted(false);
        btninventory.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btninventory.addActionListener(this::btninventoryActionPerformed);
        add(btninventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, 200, 190));

        btnshipment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ifccrafts/assets/shipment.png"))); // NOI18N
        btnshipment.setBorderPainted(false);
        btnshipment.setContentAreaFilled(false);
        btnshipment.setFocusPainted(false);
        btnshipment.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnshipment.addActionListener(this::btnshipmentActionPerformed);
        add(btnshipment, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, 200, 190));

        btnaffiliate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ifccrafts/assets/affiliate.png"))); // NOI18N
        btnaffiliate.setBorderPainted(false);
        btnaffiliate.setContentAreaFilled(false);
        btnaffiliate.setFocusPainted(false);
        btnaffiliate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnaffiliate.addActionListener(this::btnaffiliateActionPerformed);
        add(btnaffiliate, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 430, 200, 190));

        btndashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ifccrafts/assets/dashboard.png"))); // NOI18N
        btndashboard.setBorderPainted(false);
        btndashboard.setContentAreaFilled(false);
        btndashboard.setFocusPainted(false);
        btndashboard.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btndashboard.addActionListener(this::btndashboardActionPerformed);
        add(btndashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 430, 200, 190));

        btntransaction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ifccrafts/assets/transaction.png"))); // NOI18N
        btntransaction.setBorderPainted(false);
        btntransaction.setContentAreaFilled(false);
        btntransaction.setFocusPainted(false);
        btntransaction.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btntransaction.addActionListener(this::btntransactionActionPerformed);
        add(btntransaction, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 210, 200, 190));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ifccrafts/assets/back.png"))); // NOI18N
        back.setBorderPainted(false);
        back.setContentAreaFilled(false);
        back.setFocusPainted(false);
        back.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        back.addActionListener(this::backActionPerformed);
        add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 75, -1, 77));

        mainbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ifccrafts/assets/mainbg.png"))); // NOI18N
        add(mainbg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 850));
    }// </editor-fold>//GEN-END:initComponents

    private void btncustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncustomerActionPerformed
        javax.swing.JFrame frame =
            (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);

        frame.setContentPane(new customer());
        frame.revalidate();
        frame.repaint();
    }//GEN-LAST:event_btncustomerActionPerformed

    private void btnproductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproductActionPerformed
        javax.swing.JFrame frame =
            (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);

        frame.setContentPane(new product());
        frame.revalidate();
        frame.repaint(); 
    }//GEN-LAST:event_btnproductActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        int choice = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "This will log you out. Continue?",
            "Confirm Logout",
            javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (choice == javax.swing.JOptionPane.YES_OPTION) {
            javax.swing.JFrame frame =
                    (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);

            frame.setContentPane(new loginpage());
            frame.revalidate();
            frame.repaint();
        }
    }//GEN-LAST:event_backActionPerformed

    private void btnorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnorderActionPerformed
        javax.swing.JFrame frame =
            (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);

        frame.setContentPane(new orderpages());
        frame.revalidate();
        frame.repaint(); 
    }//GEN-LAST:event_btnorderActionPerformed

    private void btntransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntransactionActionPerformed
        javax.swing.JFrame frame =
            (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);

        frame.setContentPane(new transactions());
        frame.revalidate();
        frame.repaint(); 
    }//GEN-LAST:event_btntransactionActionPerformed

    private void btnshipmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnshipmentActionPerformed
        javax.swing.JFrame frame =
            (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);

        frame.setContentPane(new shipments());
        frame.revalidate();
        frame.repaint(); 
    }//GEN-LAST:event_btnshipmentActionPerformed

    private void btninventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninventoryActionPerformed
        javax.swing.JFrame frame =
            (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);

        frame.setContentPane(new inventory());
        frame.revalidate();
        frame.repaint();
    }//GEN-LAST:event_btninventoryActionPerformed

    private void btnaffiliateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaffiliateActionPerformed
        javax.swing.JFrame frame =
            (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);

        frame.setContentPane(new affiliate());
        frame.revalidate();
        frame.repaint();
    }//GEN-LAST:event_btnaffiliateActionPerformed

    private void btndashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndashboardActionPerformed
        javax.swing.JFrame frame =
            (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);

        frame.setContentPane(new dashboard());
        frame.revalidate();
        frame.repaint();
    }//GEN-LAST:event_btndashboardActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton btnaffiliate;
    private javax.swing.JButton btncustomer;
    private javax.swing.JButton btndashboard;
    private javax.swing.JButton btninventory;
    private javax.swing.JButton btnorder;
    private javax.swing.JButton btnproduct;
    private javax.swing.JButton btnshipment;
    private javax.swing.JButton btntransaction;
    private javax.swing.JLabel mainbg;
    // End of variables declaration//GEN-END:variables

}



