
import java.awt.FontFormatException;
import java.io.IOException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author hezekiahmagalona
 */
public class loginpage extends javax.swing.JPanel {

    private java.awt.Font customFont;

    /**
     * Creates new form loginpage
     */
    public loginpage() {
        initComponents();

        loadFonts();

        name.setFont(customFont.deriveFont(java.awt.Font.BOLD, 28f));
        password.setFont(customFont.deriveFont(java.awt.Font.PLAIN, 24f));

        password.setEchoChar('•');

        password.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                new javax.swing.border.LineBorder(java.awt.Color.GRAY, 2, true),
                javax.swing.BorderFactory.createEmptyBorder(0, 12, 0, 45)
        ));

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        picon = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        showpassword = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        login = new javax.swing.JButton();
        mainbg = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        picon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ifccrafts/assets/picon.png"))); // NOI18N
        add(picon, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 80, 80));

        name.setFont(new java.awt.Font("Snell Roundhand", 1, 28)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name.setText("Ifalyn Calderon");
        add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, 200, 40));

        exit.setBackground(new java.awt.Color(255, 255, 255));
        exit.setFont(new java.awt.Font("Kokonor", 0, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(0, 0, 0));
        exit.setText("Exit");
        exit.addActionListener(this::exitActionPerformed);
        add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 490, 90, 40));

        showpassword.setBackground(new java.awt.Color(255, 255, 255));
        showpassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ifccrafts/assets/spass.png"))); // NOI18N
        showpassword.setBorderPainted(false);
        showpassword.setContentAreaFilled(false);
        showpassword.setFocusPainted(false);
        showpassword.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        showpassword.addActionListener(this::showpasswordActionPerformed);
        add(showpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 420, 50, 50));

        password.setBackground(new java.awt.Color(255, 255, 255));
        password.setFont(new java.awt.Font("Kokonor", 0, 18)); // NOI18N
        password.setForeground(new java.awt.Color(0, 0, 0));
        password.addActionListener(this::passwordActionPerformed);
        add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 420, 280, 50));

        login.setBackground(new java.awt.Color(255, 255, 255));
        login.setFont(new java.awt.Font("Kokonor", 0, 18)); // NOI18N
        login.setForeground(new java.awt.Color(0, 0, 0));
        login.setText("Log in");
        login.addActionListener(this::loginActionPerformed);
        add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 490, 90, 40));
        add(mainbg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ifccrafts/assets/mainbg.png"))); // NOI18N
        add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 850));
    }// </editor-fold>//GEN-END:initComponents

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void showpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpasswordActionPerformed
        String pass = String.valueOf(password.getPassword());

        if (!pass.equals("Password")) {
            if (password.getEchoChar() == (char) 0) {
                password.setEchoChar('•');
                showpassword.setText("");
            } else {
                password.setEchoChar((char) 0);
                showpassword.setText("");
            }}
    }//GEN-LAST:event_showpasswordActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        String pass = String.valueOf(password.getPassword());

        if (pass.equals("123")) {
            javax.swing.JFrame frame =
                (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);

            frame.setContentPane(new homepage());
            frame.revalidate();
            frame.repaint();
        } else {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Incorrect password.",
                "Login Failed",
                javax.swing.JOptionPane.ERROR_MESSAGE
            );

            password.setText("");
            password.requestFocus();
        }
    }//GEN-LAST:event_loginActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        int choice = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "This will exit the system. Continue?",
            "Confirm Exit",
            javax.swing.JOptionPane.YES_NO_OPTION
    );

    if (choice == javax.swing.JOptionPane.YES_OPTION) {
        System.exit(0);
    }

    }//GEN-LAST:event_exitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton exit;
    private javax.swing.JButton login;
    private javax.swing.JLabel mainbg;
    private javax.swing.JLabel name;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel picon;
    private javax.swing.JButton showpassword;
    // End of variables declaration//GEN-END:variables

    private void loadFonts() {
        try {
            customFont = java.awt.Font.createFont(
                    java.awt.Font.TRUETYPE_FONT,
                    getClass().getResourceAsStream("/ifccrafts/assets/MyFont.ttf")
            );
        } catch (FontFormatException | IOException e) {
            customFont = new java.awt.Font("Serif", java.awt.Font.PLAIN, 18);
        }
    }
}