/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author hezekiahmagalona
 */
public class orderpages extends javax.swing.JPanel {

    private java.awt.CardLayout layout;
    private javax.swing.JPanel container;

    /**
     *
     * Creates new form homepage1
     */
    public orderpages() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnorderitem = new javax.swing.JButton();
        back = new javax.swing.JButton();
        btnorder = new javax.swing.JButton();
        mainbg = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnorderitem.setIcon(new javax.swing.ImageIcon("/Users/hezekiahmagalona/NetBeansProjects/IFCCRAFTS/src/ifccrafts/assets/orderitem.png")); // NOI18N
        btnorderitem.setBorderPainted(false);
        btnorderitem.setContentAreaFilled(false);
        btnorderitem.setFocusPainted(false);
        btnorderitem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnorderitem.addActionListener(this::btnorderitemActionPerformed);
        add(btnorderitem, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 320, 200, 190));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ifccrafts/assets/back.png"))); // NOI18N
        back.setBorderPainted(false);
        back.setContentAreaFilled(false);
        back.setFocusPainted(false);
        back.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        back.addActionListener(this::backActionPerformed);
        add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 75, -1, 77));

        btnorder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ifccrafts/assets/order.png"))); // NOI18N
        btnorder.setBorderPainted(false);
        btnorder.setContentAreaFilled(false);
        btnorder.setFocusPainted(false);
        btnorder.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnorder.addActionListener(this::btnorderActionPerformed);
        add(btnorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, 200, 190));

        mainbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ifccrafts/assets/mainbg.png"))); // NOI18N
        add(mainbg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 850));
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        javax.swing.JFrame frame =
        (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);

        frame.setContentPane(new homepage());
        frame.revalidate();
        frame.repaint();
    }//GEN-LAST:event_backActionPerformed

    private void btnorderitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnorderitemActionPerformed
        javax.swing.JFrame frame =
        (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);

        frame.setContentPane(new orderitem());
        frame.revalidate();
        frame.repaint();
    }//GEN-LAST:event_btnorderitemActionPerformed

    private void btnorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnorderActionPerformed
        javax.swing.JFrame frame =
        (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);

        frame.setContentPane(new order());
        frame.revalidate();
        frame.repaint();
    }//GEN-LAST:event_btnorderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton btnorder;
    private javax.swing.JButton btnorderitem;
    private javax.swing.JLabel mainbg;
    // End of variables declaration//GEN-END:variables

}



